<?php echo $this->getContent();?>

	<div class="row">
		<div class="col s12 m6 offset-m3 grey-text text-darken-2 center">
			<h3>Historial de Accesos</h3>
		</div>
	</div>


<div class="container" style="margin-top: 30px;">
	
	<div class="row">
		<div class="col s12 m10 offset-m1">
			<table class="responsive-table centered" >
		        <thead>
		          <tr class="white-text  light-blue darken-4 center">
		              <!--th>Matrícula</th>
		              <th>Nombre Completo</th>
		              <th>Bici</th>
		              <th>Acción</th>
		              <th>Acceso</th>
		              <th>Fecha / Hora</th-->

		              <th>MATRÍCULA</th>
		              <th>NOMBRE COMPLETO</th>
		              <th>BICI</th>
		              <th>ACCIÓN</th>
		              <th>ACCESO</th>
		              <th>FECHA / HORA</th>
		          </tr>
		        </thead>

		        <tbody >
		        	<?php 
		        		if(isset($Registros)){
		        			foreach ($Registros as $registro) {
		        			
		        	?>
							<tr>
					            <td><?php echo $registro->Id_Persona;?></td>
					            <td>
					            	<?php echo $registro->Nombre." ".$registro->Ap_Paterno." ".$registro->Ap_Materno;?>
					            </td>
					            <td>
					            	<?php echo ($registro->Id_Bici > 0)? $registro->Id_Bici:"---";?>
					            </td>
					            <td>
					            	<?php echo ($registro->Accion == 'E')? 
					            	"<a class=\"black-text blue lighten-3\">Entró</a>":
					            	"<a class=\"black-text orange lighten-3\">Salió</a>";
					            	?>
					            </td>
					            <td><?php echo $registro->Nombre_A;?></td>
					            <td><?php echo $registro->Fecha_Hora;?></td>
					        </tr>

		        	<?php

		        			}
		        		}
		        	?>
		          
		          
		        </tbody>
		    </table>
		</div>
	</div>
</div>

	
